# Generated by Django 3.0.3 on 2020-03-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True, verbose_name='No')),
                ('ppm_ch4', models.CharField(blank=True, max_length=50, null=True, verbose_name='ppm CH4')),
                ('ppm_c2h4', models.CharField(blank=True, max_length=50, null=True, verbose_name='ppm C2H4')),
                ('ppm_c2h2', models.CharField(blank=True, max_length=50, null=True, verbose_name='ppm C2H2')),
                ('persen_ch4', models.CharField(blank=True, max_length=50, null=True, verbose_name='%CH4')),
                ('persen_c2h4', models.CharField(blank=True, max_length=50, null=True, verbose_name='%C2H4')),
                ('persen_c2h2', models.CharField(blank=True, max_length=50, null=True, verbose_name='%C2H2')),
                ('fault', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fault')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
