# Generated by Django 3.0.4 on 2020-05-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True, verbose_name='No')),
                ('persen_ch4', models.CharField(blank=True, max_length=50, null=True, verbose_name='%CH4')),
                ('persen_c2h4', models.CharField(blank=True, max_length=50, null=True, verbose_name='%C2H4')),
                ('persen_c2h2', models.CharField(blank=True, max_length=50, null=True, verbose_name='%C2H2')),
                ('fault', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fault')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('lamda', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lambda')),
                ('sigma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sigma')),
                ('constant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Constant')),
                ('gamma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gamma')),
                ('iterasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Iterasi')),
            ],
        ),
    ]
