# Generated by Django 3.0.4 on 2020-03-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='ppm_c2h2',
        ),
        migrations.RemoveField(
            model_name='data',
            name='ppm_c2h4',
        ),
        migrations.RemoveField(
            model_name='data',
            name='ppm_ch4',
        ),
    ]
