# Generated by Django 3.0.4 on 2020-06-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='akurasi',
            field=models.CharField(max_length=50, null=True, verbose_name='Akurasi'),
        ),
    ]
