# Generated by Django 3.0.4 on 2020-05-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True, verbose_name='No')),
                ('persen_ch4', models.CharField(blank=True, max_length=50, null=True, verbose_name='%CH4')),
                ('persen_c2h4', models.CharField(blank=True, max_length=50, null=True, verbose_name='%C2H4')),
                ('persen_c2h2', models.CharField(blank=True, max_length=50, null=True, verbose_name='%C2H2')),
                ('fault', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fault')),
                ('hasil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hasil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
