# Generated by Django 3.0.4 on 2020-06-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_diagnosis_akurasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='f7',
            field=models.CharField(max_length=50, null=True, verbose_name='f7'),
        ),
    ]
