# Generated by Django 3.0.4 on 2020-05-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_datatesting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Level')),
                ('bias', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bias')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='DataTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, null=True, verbose_name='No')),
                ('level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Level')),
                ('persen_ch4', models.CharField(blank=True, max_length=50, null=True, verbose_name='%CH4')),
                ('persen_c2h4', models.CharField(blank=True, max_length=50, null=True, verbose_name='%C2H4')),
                ('persen_c2h2', models.CharField(blank=True, max_length=50, null=True, verbose_name='%C2H2')),
                ('fault', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fault')),
                ('kelas', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kelas')),
                ('alpha', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alpha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
